### ISSUE TITLE
包的名字取的真奇葩

### ISSUE THREAD

**Issue by lpjia** [chana1024/linzhinan-vue-code-link#5]
尬

**Comment by lpjia** [comment]
试用了下, 发现从我点击 dom 开始计时, 到 vscode 能正确跳到对应代码, 时间还是挺长的, 同时编辑器直接卡住, 一综合, 感觉很鸡肋...况且我发现 vue-devtools 这个工具也有跳转到组件的功能(仅仅到组件), 但是时间上要快很多, 所以推荐先优化性能

**Comment by chana1024** [comment]
我自己平时使用速度是很快的，如主页的动态图所示。建议更新到最新版本再试试。
至于包名，毕竟是我自己的包，怎么取是我的自由，不喜欢可以不用，谢谢！
