### ISSUE TITLE
关于antdv的tree组件bug

### ISSUE THREAD

**Issue by cooper1x** [chana1024/linzhinan-vue-code-link#7]
```
<a-tree v-model="checkedKeys" :treeData="treeData" :selectedKeys="selectedKeys" :expandedKeys="expandedKeys" @expand="onExpand" :autoExpandParent="autoExpandParent" :replaceFields="replaceFields" @select="onSelect" :show-line="true">
          <template slot="title" slot-scope="{ name }">
            <span v-html="
                name.replace(
                  new RegExp(searchValue, 'g'),
                  '<span style=color:#f50>' + searchValue + '</span>'
                )
              "></span>
          </template>
        </a-tree>
```
如果a-tree里面套了一个template，template里面有span标签用了v-html的js代码，比方说上面这个，插件会把其中的html字符串给加上行号，导致页面显示是这样的。
<img width="330" alt="image" src="https://user-images.githubusercontent.com/9080789/190978844-f4a358cb-931e-4a94-af5a-39870ccf12b3.png">

**Comment by chana1024** [comment]
可以把页面源码发来看下吗。看被处理成什么样

**Comment by cooper1x** [comment]
不好意思，才看到，我花了点时间，写了个线上demo，麻烦抽空看看哈。
https://stackblitz.com/edit/vue2-vue-cli-gswaaz?file=src/components/HelloWorld.vue
### 正常是这样的：
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/9080789/204180008-3c0c7bf3-20cd-48e2-8a99-37ac5d83fa41.png">

### 开启了@linzhinan-vue-code-link，刷新下页面是这样的：
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/9080789/204180145-3910931c-fc6b-4b54-91a8-60b0f9446c97.png">

**Comment by chana1024** [comment]
我做了次升级，请升级到1.0.36再试一下。我没有用语法树解析代码，确实容易出现这类问题

**Comment by cooper1x** [comment]
@chana1024 我这边升级版本可以了，太棒了！

**Comment by chana1024** [comment]
好的，谢谢你的反馈
